# Generated by Django 3.2.10 on 2022-01-11 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_fill_db'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-city',), 'verbose_name': 'контактов', 'verbose_name_plural': 'контакты'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-price',), 'verbose_name': 'товаров', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('-pk',), 'verbose_name': 'категория товаров', 'verbose_name_plural': 'категории товаров'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.productcategory', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='название'),
        ),
    ]
