# Generated by Django 3.2.10 on 2022-01-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ('-pk',), 'verbose_name': 'корзина', 'verbose_name_plural': 'корзины пользователей'},
        ),
    ]
