# Generated by Django 3.2.12 on 2022-02-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0008_create_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='email'),
        ),
    ]
